import type { Metadata } from 'next'
import { CATEGORIES, ACCENT_CLASSES } from '@/lib/categories'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'About',
}

export default function AboutPage() {
  return (
    <div className="mx-auto max-w-2xl px-4 py-12 md:px-0">
      <header className="mb-10">
        <span className="mb-3 block text-xs font-semibold uppercase tracking-widest text-gray-500">
          About
        </span>
        <h1 className="font-serif-display text-4xl font-bold italic text-white md:text-5xl">
          My Daily Clippings.
        </h1>
      </header>

      <div className="space-y-6 text-base leading-relaxed text-gray-300">
        <p>
          <strong className="text-white">My Daily Clippings</strong> is a personal newspaper built for
          one reader. Every morning at 6AM, an AI agent scans the latest developments across science,
          technology, and world affairs, then drafts a curated briefing in the style of a personal journal.
        </p>
        <p>
          Not a news aggregator. Not a social feed. Think of it as a brilliant correspondent who reads
          everything so you don&apos;t have to, then writes it up in language worth reading.
        </p>
        <p>
          Powered by{' '}
          <span className="text-white">Google Gemini</span> with real-time web search, published daily
          to this site via GitHub Actions.
        </p>
      </div>

      {/* Categories */}
      <section className="mt-12">
        <h2 className="mb-5 font-serif-display text-xl font-bold text-white">Current Sections</h2>
        <div className="space-y-3">
          {CATEGORIES.map((cat) => {
            const accent = ACCENT_CLASSES[cat.accentColor]
            return (
              <Link
                key={cat.slug}
                href={`/${cat.slug}`}
                className="flex items-start gap-4 rounded-xl border border-surface-border bg-surface-card p-4 transition-colors hover:border-gray-600"
              >
                <span className={`mt-0.5 text-xs font-bold uppercase tracking-widest ${accent.text}`}>
                  {cat.label}
                </span>
                <p className="text-sm text-gray-400">{cat.tagline}</p>
              </Link>
            )
          })}
        </div>
      </section>

      <p className="mt-12 text-sm text-gray-600">
        Built with Next.js · Hosted on GitHub Pages · Generated by Gemini 2.5 Flash
      </p>
    </div>
  )
}
